[package]
name = "wycheproof-types"
authors = ["Enrik Berkhan <Enrik.Berkhan@inka.de>"]
description = "Project Wycheproof no-std types for salty."
edition.workspace = true
license.workspace = true
version = "0.1.0"
