[package]
name = "wycheproof-types"
authors = ["Enrik Berkhan <Enrik.Berkhan@inka.de>"]
description = "Project Wycheproof tests for salty: no-std types."
edition.workspace = true
license.workspace = true
version.workspace = true
